title: "Maumita Bhaumik [ˈmoumit̪a ˈbʱoumik]"
author: "Maumita"
#description: "English & Foreign Languages University"
description: "Copyright © 2023 Maumita Bhaumik"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site (true/false)
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Research", file: "research.md"}
  - {title: "Papers & Presentations", file: "papers_and_presentations.md"}
  - {title: "CV", file: "cv.md"}
  - {title: "Blog", file: "blog.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:moumitaphdlandp19@efluniversity.ac.in"}
  - {title: Github, icon: github, url: "https://github.com/maumitabhaumik"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/maumita-bhaumik-669722156/"}
  - {title: Google scholar, icon: graduation-cap, url: "https://scholar.google.com/citations?user=PupexxsAAAAJ&hl=en&oi=ao"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/Maumita-Bhaumik"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-seo-tag  #Maumita added it for favicon
